Repository superfluid-finance/superfluid-sentinel, pull requests merged in 2023-04, with the labels that each got.

#189 [fix] reduce eth_blockNumber by one, using provided block offset
  src/boot/loadEvents.js
Labels: Severity: Low

#190 add TelegramNotifier
  .env-example
  package-lock.json
  package.json
  src/app.js
  src/config/configuration.js
  src/services/telegramNotifier.js
Labels: Type: Enhancement

#199 get startBlockV1 as EPOCH
  src/config/configuration.js
Labels: Tag: Hotfix, Team: Protocol, Project: SENTINEL

#196 Fix #195 - First gas estimation can go above defined limit
  src/transaction/gas.js
  src/web3client/liquidator.js
Labels: Team: Protocol, Project: SENTINEL

#204 Fix Gas Call Method
  src/transaction/gas.js
Labels: Type: Bug, Team: Protocol, Project: SENTINEL

#206 fix block ranges on error
  scripts/buildSnapshot.js
  src/boot/loadEvents.js
Labels: Severity: Critical, Team: Protocol, Project: SENTINEL
